version: '3.4'

services:
  levsundt.webapp:
    ports:
      - "32333:80"
    image: ${DOCKER_REGISTRY-}levsundtwebapp
    build:
      context: .
      dockerfile: ./LevSundt.WebApp/Dockerfile


  levsundt.api:
    image: ${DOCKER_REGISTRY-}levsundtapi
    build:
      context: .
      dockerfile: ./LevSundt.Api/Dockerfile

