version: '3.4'

services:
  levsundt.webapp:
    ports:
      - "32333:80"
    image: ${DOCKER_REGISTRY-}levsundtwebapp
    build:
      context: .
      dockerfile: ./LevSundt.WebApp/Dockerfile
    depends_on:
      - db
      - levsundt.api


  levsundt.api:
    image: ${DOCKER_REGISTRY-}levsundtapi
    build:
      context: .
      dockerfile: ./LevSundt.Api/Dockerfile
    depends_on:
      - db
  
#https://github.com/Microsoft/mssql-docker/issues/283 change password
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "14330:1433"
    environment:
        MSSQL_SA_PASSWORD: "sa"
        ACCEPT_EULA: "Y"
    volumes:
      - C:\DockerVolumes\sqlserver:/var/opt/mssql/data 