USE [master]
GO
CREATE LOGIN [web] WITH PASSWORD=N'webPassw0rd!', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [api] WITH PASSWORD=N'apiPassw0rd!', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO



