USE [master]
CREATE DATABASE [LevSundtUsers]
GO
ALTER DATABASE [LevSundtUsers] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LevSundtUsers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LevSundtUsers] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LevSundtUsers] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LevSundtUsers] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LevSundtUsers] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LevSundtUsers] SET ARITHABORT OFF 
GO
ALTER DATABASE [LevSundtUsers] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LevSundtUsers] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LevSundtUsers] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LevSundtUsers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LevSundtUsers] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LevSundtUsers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LevSundtUsers] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LevSundtUsers] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LevSundtUsers] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LevSundtUsers] SET  ENABLE_BROKER 
GO
ALTER DATABASE [LevSundtUsers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LevSundtUsers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LevSundtUsers] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LevSundtUsers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LevSundtUsers] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LevSundtUsers] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [LevSundtUsers] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LevSundtUsers] SET RECOVERY FULL 
GO
ALTER DATABASE [LevSundtUsers] SET  MULTI_USER 
GO
ALTER DATABASE [LevSundtUsers] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LevSundtUsers] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LevSundtUsers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LevSundtUsers] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LevSundtUsers] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LevSundtUsers] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'LevSundtUsers', N'ON'
GO
ALTER DATABASE [LevSundtUsers] SET QUERY_STORE = OFF
GO


CREATE DATABASE [LevSundtDomain]
GO
ALTER DATABASE [LevSundtDomain] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LevSundtDomain].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LevSundtDomain] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LevSundtDomain] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LevSundtDomain] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LevSundtDomain] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LevSundtDomain] SET ARITHABORT OFF 
GO
ALTER DATABASE [LevSundtDomain] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LevSundtDomain] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LevSundtDomain] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LevSundtDomain] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LevSundtDomain] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LevSundtDomain] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LevSundtDomain] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LevSundtDomain] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LevSundtDomain] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LevSundtDomain] SET  ENABLE_BROKER 
GO
ALTER DATABASE [LevSundtDomain] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LevSundtDomain] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LevSundtDomain] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LevSundtDomain] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LevSundtDomain] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LevSundtDomain] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [LevSundtDomain] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LevSundtDomain] SET RECOVERY FULL 
GO
ALTER DATABASE [LevSundtDomain] SET  MULTI_USER 
GO
ALTER DATABASE [LevSundtDomain] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LevSundtDomain] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LevSundtDomain] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LevSundtDomain] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LevSundtDomain] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LevSundtDomain] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'LevSundtDomain', N'ON'
GO
ALTER DATABASE [LevSundtDomain] SET QUERY_STORE = OFF
GO